# Generated by Django 2.1.7 on 2019-03-12 22:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tdmilleranalytics_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdmilleranalytics_resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeItemLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('resume_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdmilleranalytics_resume.ResumeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeItemShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=30)),
                ('rating_percent', models.IntegerField()),
                ('resume_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdmilleranalytics_resume.ResumeCategory')),
            ],
        ),
    ]
