# Generated by Django 2.1.7 on 2019-03-13 01:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdmilleranalytics_resume', '0002_resumecategory_resumeitemlong_resumeitemshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resumecategory',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
