# Generated by Django 2.1.7 on 2019-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdmilleranalytics_resume', '0003_auto_20190312_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitemlong',
            name='end',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitemlong',
            name='organization',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitemlong',
            name='start',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitemshort',
            name='rating_percent',
            field=models.IntegerField(null=True),
        ),
    ]
