# Generated by Django 2.1.7 on 2019-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdmilleranalytics_resume', '0005_auto_20190314_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitemshort',
            name='item_text',
            field=models.CharField(max_length=45),
        ),
    ]
